title: Barb Hernández
url: http://barbhernandez.com

permalink: pretty
auto: true
server: true
lsi: false
pygments: true

exclude: private

nav:
  - text: Inicio
    path: /

  - text: Proyectos
    path: /proyectos/

  - text: CV
    path: /cv/

  - text: Contacto
    path: /contacto/






